# a cluster with 1 control-plane nodes and 1 workers
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: lab03
nodes:
- role: control-plane
  #image: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"

  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        seccomp-default: "true"  

  - |
    kind: ClusterConfiguration
    apiServer:
        # enable auditing flags on the API server
        extraArgs:
          audit-log-path: "/var/log/kubernetes/kube-apiserver-audit.log"
          audit-policy-file: "/etc/kubernetes/policies/audit-policy.yaml"
          # defined the maximum number of days to retain old audit log files
          audit-log-maxage: "5"
          # defines the maximum number of audit log files to retain
          audit-log-maxbackup: "2"
          # defines the maximum size in megabytes of the audit log file before it gets rotated
          audit-log-maxsize: "100"
        # mount new files / directories on the control plane
        extraVolumes:
          - name: audit-policies
            hostPath: "/etc/kubernetes/policies"
            mountPath: "/etc/kubernetes/policies"
            readOnly: true
            pathType: DirectoryOrCreate
          - name: audit-logs
            hostPath: "/var/log/kubernetes"
            mountPath: "/var/log/kubernetes"
            readOnly: false
            pathType: DirectoryOrCreate


  # mount the local file on the control plane
  extraMounts:
  # local audit policy
  - hostPath: ./audit-policy.yaml
    containerPath: /etc/kubernetes/policies/audit-policy.yaml
    readOnly: true

  # store logs locally
  - hostPath: ./logs/
    containerPath: /var/log/kubernetes/
    readOnly: false

  # seccomp profiles
  - hostPath: ./profiles
    containerPath: /var/lib/kubelet/seccomp/profiles

#  extraPortMappings:
#  - containerPort: 80
#    hostPort: 80
#    protocol: TCP
#  - containerPort: 443
#    hostPort: 443
#    protocol: TCP
#  - containerPort: 4244
#    hostPort: 4244
#    protocol: TCP
#  - containerPort: 4245
#    hostPort: 4245
#    protocol: TCP



- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        feature-gates: SeccompDefault=true
        seccomp-default: "true"
#- role: worker
#  kubeadmConfigPatches:
#  - |
#    kind: JoinConfiguration
#    nodeRegistration:
#      kubeletExtraArgs:
#        feature-gates: SeccompDefault=true
#        seccomp-default: "true"
#- role: worker
#  kubeadmConfigPatches:
#  - |
#    kind: JoinConfiguration
#    nodeRegistration:
#      kubeletExtraArgs:
#        feature-gates: SeccompDefault=true
#        seccomp-default: "true"



#  https://docs.cilium.io/en/stable/gettingstarted/kind/
networking:
  #ipFamily: ipv4
  disableDefaultCNI: true
  # lab id at octet 2
  # cilium wont install in less than /16 subnet oddly
  podSubnet: "10.3.0.0/16"
  serviceSubnet: "10.4.0.0/16"


