apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: old-nginx
  name: old-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: old-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: old-nginx
    spec:
      containers:
      # 1.19.9 is a year old in May'22
      - image: nginx:1.19.9
        name: old-nginx-container
        resources: {}
status: {}
