apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: old-nginx
  name: old-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: old-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: old-nginx
    spec:
      containers:
      - image: nginx:1.9
        name: nginx
        resources: {}
status: {}
